spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000 # 30초까지 대기
      validation-timeout: 5000  # 5초 안에 연결 확인
      maximum-pool-size: 5
      initialization-fail-timeout: -1 # 초기 연결 실패해도 재시도

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  exp-ms: ${JWT_EXP:3600000}
