spring:
  datasource:
      url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: ${MYSQLUSER}
      password: ${MYSQLPASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  exp-ms: ${JWT_EXP:3600000}
